<?php

namespace ContainerXuSI9FK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BcQbrgGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bcQbrgG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bcQbrgG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::dashboard' => ['privates', '.service_locator.Wxf6IJb', 'get_ServiceLocator_Wxf6IJbService', true],
            'App\\Controller\\CartController::_shoppingCartList' => ['privates', '.service_locator.4z6FS8y', 'get_ServiceLocator_4z6FS8yService', true],
            'App\\Controller\\CartController::addItemToCart' => ['privates', '.service_locator.wTaMKdU', 'get_ServiceLocator_WTaMKdUService', true],
            'App\\Controller\\CartController::removeItemToCart' => ['privates', '.service_locator.quvDhFe', 'get_ServiceLocator_QuvDhFeService', true],
            'App\\Controller\\CartController::shoppingCart' => ['privates', '.service_locator.CqVu78O', 'get_ServiceLocator_CqVu78OService', true],
            'App\\Controller\\CheckoutController::checkout' => ['privates', '.service_locator.h4bGV_s', 'get_ServiceLocator_H4bGVSService', true],
            'App\\Controller\\CheckoutController::confirmation' => ['privates', '.service_locator.Ls9fPxb', 'get_ServiceLocator_Ls9fPxbService', true],
            'App\\Controller\\ProductAdminController::delete' => ['privates', '.service_locator.iyEwlLH', 'get_ServiceLocator_IyEwlLHService', true],
            'App\\Controller\\ProductAdminController::edit' => ['privates', '.service_locator.iyEwlLH', 'get_ServiceLocator_IyEwlLHService', true],
            'App\\Controller\\ProductAdminController::index' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.sykwclQ', 'get_ServiceLocator_SykwclQService', true],
            'App\\Controller\\ProductController::productReviews' => ['privates', '.service_locator..N.D9yy', 'get_ServiceLocator__N_D9yyService', true],
            'App\\Controller\\ProductController::showProduct' => ['privates', '.service_locator.IvJHccu', 'get_ServiceLocator_IvJHccuService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.qbwTkM3', 'get_ServiceLocator_QbwTkM3Service', true],
            'App\\Controller\\ReviewAdminController::delete' => ['privates', '.service_locator.Z7x75EX', 'get_ServiceLocator_Z7x75EXService', true],
            'App\\Controller\\ReviewAdminController::edit' => ['privates', '.service_locator.Z7x75EX', 'get_ServiceLocator_Z7x75EXService', true],
            'App\\Controller\\ReviewAdminController::index' => ['privates', '.service_locator.OEREEZh', 'get_ServiceLocator_OEREEZhService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AdminController:dashboard' => ['privates', '.service_locator.Wxf6IJb', 'get_ServiceLocator_Wxf6IJbService', true],
            'App\\Controller\\CartController:_shoppingCartList' => ['privates', '.service_locator.4z6FS8y', 'get_ServiceLocator_4z6FS8yService', true],
            'App\\Controller\\CartController:addItemToCart' => ['privates', '.service_locator.wTaMKdU', 'get_ServiceLocator_WTaMKdUService', true],
            'App\\Controller\\CartController:removeItemToCart' => ['privates', '.service_locator.quvDhFe', 'get_ServiceLocator_QuvDhFeService', true],
            'App\\Controller\\CartController:shoppingCart' => ['privates', '.service_locator.CqVu78O', 'get_ServiceLocator_CqVu78OService', true],
            'App\\Controller\\CheckoutController:checkout' => ['privates', '.service_locator.h4bGV_s', 'get_ServiceLocator_H4bGVSService', true],
            'App\\Controller\\CheckoutController:confirmation' => ['privates', '.service_locator.Ls9fPxb', 'get_ServiceLocator_Ls9fPxbService', true],
            'App\\Controller\\ProductAdminController:delete' => ['privates', '.service_locator.iyEwlLH', 'get_ServiceLocator_IyEwlLHService', true],
            'App\\Controller\\ProductAdminController:edit' => ['privates', '.service_locator.iyEwlLH', 'get_ServiceLocator_IyEwlLHService', true],
            'App\\Controller\\ProductAdminController:index' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.sykwclQ', 'get_ServiceLocator_SykwclQService', true],
            'App\\Controller\\ProductController:productReviews' => ['privates', '.service_locator..N.D9yy', 'get_ServiceLocator__N_D9yyService', true],
            'App\\Controller\\ProductController:showProduct' => ['privates', '.service_locator.IvJHccu', 'get_ServiceLocator_IvJHccuService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.qbwTkM3', 'get_ServiceLocator_QbwTkM3Service', true],
            'App\\Controller\\ReviewAdminController:delete' => ['privates', '.service_locator.Z7x75EX', 'get_ServiceLocator_Z7x75EXService', true],
            'App\\Controller\\ReviewAdminController:edit' => ['privates', '.service_locator.Z7x75EX', 'get_ServiceLocator_Z7x75EXService', true],
            'App\\Controller\\ReviewAdminController:index' => ['privates', '.service_locator.OEREEZh', 'get_ServiceLocator_OEREEZhService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AdminController::dashboard' => '?',
            'App\\Controller\\CartController::_shoppingCartList' => '?',
            'App\\Controller\\CartController::addItemToCart' => '?',
            'App\\Controller\\CartController::removeItemToCart' => '?',
            'App\\Controller\\CartController::shoppingCart' => '?',
            'App\\Controller\\CheckoutController::checkout' => '?',
            'App\\Controller\\CheckoutController::confirmation' => '?',
            'App\\Controller\\ProductAdminController::delete' => '?',
            'App\\Controller\\ProductAdminController::edit' => '?',
            'App\\Controller\\ProductAdminController::index' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::productReviews' => '?',
            'App\\Controller\\ProductController::showProduct' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ReviewAdminController::delete' => '?',
            'App\\Controller\\ReviewAdminController::edit' => '?',
            'App\\Controller\\ReviewAdminController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:dashboard' => '?',
            'App\\Controller\\CartController:_shoppingCartList' => '?',
            'App\\Controller\\CartController:addItemToCart' => '?',
            'App\\Controller\\CartController:removeItemToCart' => '?',
            'App\\Controller\\CartController:shoppingCart' => '?',
            'App\\Controller\\CheckoutController:checkout' => '?',
            'App\\Controller\\CheckoutController:confirmation' => '?',
            'App\\Controller\\ProductAdminController:delete' => '?',
            'App\\Controller\\ProductAdminController:edit' => '?',
            'App\\Controller\\ProductAdminController:index' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:productReviews' => '?',
            'App\\Controller\\ProductController:showProduct' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ReviewAdminController:delete' => '?',
            'App\\Controller\\ReviewAdminController:edit' => '?',
            'App\\Controller\\ReviewAdminController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
