<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXuSI9FK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXuSI9FK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXuSI9FK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXuSI9FK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXuSI9FK\App_KernelDevDebugContainer([
    'container.build_hash' => 'XuSI9FK',
    'container.build_id' => '98a01591',
    'container.build_time' => 1646779322,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXuSI9FK');
