<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5D9drIx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5D9drIx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5D9drIx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5D9drIx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5D9drIx\App_KernelDevDebugContainer([
    'container.build_hash' => '5D9drIx',
    'container.build_id' => 'a2632bee',
    'container.build_time' => 1646780139,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5D9drIx');
