<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCtYLLhY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCtYLLhY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCtYLLhY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCtYLLhY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCtYLLhY\App_KernelDevDebugContainer([
    'container.build_hash' => 'CtYLLhY',
    'container.build_id' => '081ffc36',
    'container.build_time' => 1647137800,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCtYLLhY');
